### PR TITLE
Attempt to fix the no-ai skeleton bug

### PR DESCRIPTION
**Pull request by TaoismDeepLake**
Looks like this only happens with optifine installed.
Worth patching whatever.

### CODE REVIEW

**Comment by TheCyberBrick** [comment]
Thanks!

**Comment by TaoismDeepLake** [comment]
“Only those with write access to this repository can merge pull requests.”
Umm... would you merge this commit into your project?  I'm not the owner so I can not do so. 
Moreover, this project requires mo'bend things and I had trouble to build the jar myself.

**Comment by TheCyberBrick** [comment]
Yes

**Comment by Patman0021** [comment]
> Yes

So... I guess not? :(

**Comment by TaoismDeepLake** [comment]
I've no idea what's going on, either... Maybe the author doesn't have time to set up and build it again?
  @Patman0021 if you want a jar you can build it from my fork. It's not easy to build those things in mainland China as the network environment is quite different here, maybe it's easier in your spot.

**Comment by oppeyrady** [comment]
Trying to compile this mod with the fix.. not really working, can anyone compile it for me? reallly like this mod but skeletons without ai are spawning everywhere on my 1.12.2 world.

**Comment by TaoismDeepLake** [comment]
> Trying to compile this mod with the fix.. not really working, can anyone compile it for me? reallly like this mod but skeletons without ai are spawning everywhere on my 1.12.2 world.

I failed to compile it, probably because of it's mobend relations. Maybe I can make an separate mod just to stop those fake skeletons from spawning？I will give it a shot

**Comment by TaoismDeepLake** [comment]
https://github.com/TaoismDeepLake/spider2fix2/releases/tag/1.1

For those who can't wait for the official fix, install my fix mod alongside.

**Comment by ghost** [comment]
Thank you for this fix! Is this a stable fix, as far as your testing could tell?

**Comment by ghost** [comment]
> https://github.com/TaoismDeepLake/spider2fix2/releases/tag/1.1
> 
> For those who can't wait for the official fix, install my fix mod alongside.

I'm still getting the NoAI skeleton bug even with your fix installed :/

**Comment by TaoismDeepLake** [comment]
Well I haven't fully tested it, as those skeletons are not easy to manual spawn. I will keep looking into it when I have time.
My testing only covered my own manual trigger method, it worked for me, as for why it doesn't work for this mod will need telling. Are you sure that my mod is loaded? You can see it in the mod list in game.
@roccscout

**Comment by ghost** [comment]
@TaoismDeepLake did you ever get to take a look at this?

**Comment by TaoismDeepLake** [comment]
> @TaoismDeepLake did you ever get to take a look at this?

If you mean "skeleton bug" by "this"...
No. I have never seen those skeletons on my computer. I heard this from the community and gave a rough guess on the problem, yet failing to reproduce the problem on my computer. I have been too confident on this issue.

If you mean this issue by "this"...
No. I have been too busy on my daytime job and my own other mods, hence failing to look this up. 


I guess I will close this PR. The author surely gets my point now, if the author wants to apply this fix, he/she is welcomed to do so.

**Pull request closed without merging**
